<div class="space-y-6">
    <section class="flex flex-col gap-4 rounded-2xl border border-white/70 bg-white/85 p-5 shadow-xl shadow-slate-950/[0.04] backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/70 sm:flex-row sm:items-center sm:justify-between">
        <div><p class="text-sm font-medium text-slate-500 dark:text-slate-400">تنظیمات سیستم</p><h2 class="mt-1 text-2xl font-bold tracking-normal text-slate-950 dark:text-white">کاربران</h2></div>
        <x-ui.button href="{{ route('users.create') }}" icon="plus" wire:navigate>ثبت کاربر</x-ui.button>
    </section>
    @if (session('status')) <x-ui.alert variant="success" dismissible>{{ session('status') }}</x-ui.alert> @endif
    <section class="overflow-hidden rounded-2xl border border-white/70 bg-white shadow-xl shadow-slate-950/[0.04] dark:border-slate-800 dark:bg-slate-950">
        <div class="overflow-x-auto ui-scrollbar"><table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-800"><thead class="bg-slate-50 text-slate-600 dark:bg-slate-900 dark:text-slate-300"><tr><th class="px-4 py-3 text-right font-semibold">نام</th><th class="px-4 py-3 text-right font-semibold">ایمیل</th><th class="px-4 py-3 text-right font-semibold">نقش ها</th><th class="px-4 py-3 text-right font-semibold">وضعیت</th><th class="px-4 py-3 text-left font-semibold">عملیات</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white dark:divide-slate-800 dark:bg-slate-950">@forelse ($users as $user)<tr><td class="px-4 py-4 font-medium text-slate-950 dark:text-white">{{ $user->name }}</td><td class="px-4 py-4 text-slate-700 dark:text-slate-200">{{ $user->email }}</td><td class="px-4 py-4 text-slate-700 dark:text-slate-200">{{ $user->roles->pluck('name')->join(', ') ?: 'بدون نقش' }}</td><td class="px-4 py-4"><x-ui.badge variant="{{ $user->status === 'active' ? 'success' : 'neutral' }}">{{ $user->status }}</x-ui.badge></td><td class="px-4 py-4"><div class="flex justify-end"><x-ui.button type="button" size="sm" variant="danger" icon="trash" wire:click="delete({{ $user->id }})" wire:confirm="این کاربر حذف شود؟">حذف</x-ui.button></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-14 text-center text-sm text-slate-500 dark:text-slate-400">کاربری ثبت نشده است.</td></tr>@endforelse</tbody></table></div>
        @if ($users->hasPages()) <div class="border-t border-slate-200 px-4 py-3 dark:border-slate-800">{{ $users->links() }}</div> @endif
    </section>
</div>
